---
- name: Configurar máquinas
  hosts: all
  user: root
  tags: 
    - setup
  roles:
    - configure_hosts

- name: Instalar/Configurar Webservers Nginx
  hosts: webserver
  remote_user: vagrant
  become: true
  tags: web
  roles:
    - role: configure_webserver


- name: Instalar/Configurar Haproxy
  hosts: loadbalancer
  remote_user: vagrant
  become: true
  tags: install
  roles:
    - role: install_haproxy

- name: Configurar Haproxy
  hosts: loadbalancer
  remote_user: vagrant
  become: true
  tags: configure
  roles:
    - role: configure_haproxy
