---
all:
  vars:
    ambiente: virtualbox
    virtual_ip: true
    loadbalancer_virtual_ip: 192.168.50.100
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: keys/haproxy

  hosts:
    # -------- Blanceadores ---------
    lb-01:
      ansible_host: 192.168.50.11
    lb-02:
      ansible_host: 192.168.50.12
    
    # -------- Webservers ---------
    webserver-01:
      ansible_host: 192.168.50.21
    webserver-02:
      ansible_host: 192.168.50.22
   
  children:
    loadbalancer:
      hosts:
        lb-01:
        lb-02:

    webserver:
      hosts:
        webserver-01:
        webserver-02: