---
- name: Instalar pacotes de dependência do haproxy
  apt:
    pkg:
      # - haproxy
      - libipset-dev
      - keepalived
      - net-tools
      - git
      - ca-certificates
      - gcc
      - libc6-dev
      - liblua5.3-dev
      - libpcre3-dev
      - libssl-dev
      - libsystemd-dev
      - make
      - wget
      - zlib1g-dev
    state: present
    update_cache: yes

# https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/
- name: Checkout do repositório do git
  git:
    repo: "{{ haproxy_git }}"
    dest: haproxy
    version: "{{ haproxy_version }}"

- name: Fazer o build do HaProxy
  make:
    chdir: /home/vagrant/haproxy
    target: all
    params:
      TARGET: linux-glibc
      USE_LUA: 1
      USE_OPENSSL: 1
      USE_PCRE: 1
      USE_ZLIB: 1
      USE_SYSTEMD: 1
      USE_PROMEX: 1
      # EXTRA_OBJS: "contrib/prometheus-exporter/service-prometheus.o"

- name: Instalar HaProxy
  make:
    chdir: /home/vagrant/haproxy
    target: install-bin

- name: Copiar binario
  command: ln -sf /usr/local/sbin/haproxy /usr/bin/haproxy
